AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LangChain + OpenAI Lambda (container image)

Globals:
  Api:
    Cors:
      AllowMethods: "'GET, POST, OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Parameters:
  ImageUri:
    Type: String
    Description: ECR image URI for the Lambda container (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/langchain:latest)
  OpenAISecretName:
    Type: String
    Default: ''
    Description: (Optional) Name or ARN of the Secrets Manager secret containing the OpenAI key
  OpenAIModel:
    Type: String
    Default: gpt-3.5-turbo

Resources:
  LangChainExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                Resource: '*'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'

  LangChainFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      Role: !GetAtt LangChainExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          OPENAI_MODEL: !Ref OpenAIModel
          OPENAI_SECRET_NAME: !Ref OpenAISecretName
      Events:
        LangApi:
          Type: Api
          Properties:
            Path: /langchain
            Method: post

Outputs:
  ApiUrl:
    Description: "Invoke URL for the API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/langchain"
